package popups;

import java.awt.Color;

import javax.swing.JComponent;
import javax.swing.KeyStroke;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * To close the error popup press 'esc'
 * 
 * @author Roshan
 */
public class ErrorPopup extends javax.swing.JFrame {

	static String error;
	boolean darkTheme = true;
	java.awt.Color backgroundColor = new java.awt.Color(77, 77, 77);
	java.awt.Color txtColor = Color.white;

	/**
	 * Creates new form ErrorPopup
	 */
	public ErrorPopup(String error) {
		this.error = error;
		initComponents();
	}

	public ErrorPopup(String title, String error) {
		super(title);
		this.error = error;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		errorLabel = new javax.swing.JLabel();
		closeButton = new javax.swing.JButton();

		if (darkTheme) {
			darkTheme();
		}

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		errorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		errorLabel.setText(error);

		closeButton.setText("Close");
		closeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				closeButtonActionPerformed(evt);
			}
		});
		closeButton.setToolTipText("Shortcut: escape");

		java.awt.event.ActionListener escListener = new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent e) {
				dispose();
			}
		};

		getRootPane().registerKeyboardAction(escListener, KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0),
				JComponent.WHEN_IN_FOCUSED_WINDOW);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(35, 35, 35).addComponent(errorLabel,
										javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
								.addGroup(layout
										.createSequentialGroup().addGap(216, 216, 216).addComponent(closeButton,
												javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
										.addGap(183, 183, 183)))
						.addGap(42, 42, 42)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(24, 24, 24)
						.addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
						.addGap(18, 18, 18)
						.addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
						.addGap(27, 27, 27)));
		pack();
		setLocationRelativeTo(null);
		
		dispatchEvent(new java.awt.event.WindowEvent(this, java.awt.event.WindowEvent.WINDOW_GAINED_FOCUS));
	}// </editor-fold>

	private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	private void darkTheme() {
		// setContentPane(new GradientWindow());
		getContentPane().setBackground(backgroundColor);

		errorLabel.setForeground(txtColor);
		errorLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14));

		closeButton.setBackground(new java.awt.Color(0, 128, 129));
		closeButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14));

	}

	/**
	 * @param args
	 *            the command line arguments
	 *//*
		 * public static void main(String args[]) { /* Set the Nimbus look and feel
		 */
	// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
	// (optional) ">
	/*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
	 * look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 *//*
		 * try { for (javax.swing.UIManager.LookAndFeelInfo info :
		 * javax.swing.UIManager.getInstalledLookAndFeels()) { if
		 * ("Nimbus".equals(info.getName())) {
		 * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } } } catch
		 * (ClassNotFoundException ex) {
		 * java.util.logging.Logger.getLogger(ErrorPopup.class.getName()).log(java.util.
		 * logging.Level.SEVERE, null, ex); } catch (InstantiationException ex) {
		 * java.util.logging.Logger.getLogger(ErrorPopup.class.getName()).log(java.util.
		 * logging.Level.SEVERE, null, ex); } catch (IllegalAccessException ex) {
		 * java.util.logging.Logger.getLogger(ErrorPopup.class.getName()).log(java.util.
		 * logging.Level.SEVERE, null, ex); } catch
		 * (javax.swing.UnsupportedLookAndFeelException ex) {
		 * java.util.logging.Logger.getLogger(ErrorPopup.class.getName()).log(java.util.
		 * logging.Level.SEVERE, null, ex); } //</editor-fold>
		 * 
		 * /* Create and display the form
		 *//*
			 * java.awt.EventQueue.invokeLater(new Runnable() { public void run() { new
			 * ErrorPopup(error).setVisible(true); } }); }
			 */

	// Variables declaration - do not modify
	private javax.swing.JButton closeButton;
	public javax.swing.JLabel errorLabel;
	// End of variables declaration
}
