
package popups;

import java.awt.event.ActionEvent;

/**
 *
 * @author Rosha
 */
public class FinalGradeCalculator extends javax.swing.JFrame {

	/**
	 * Creates new form FinalGradeCalcGUI
	 */
	public FinalGradeCalculator() {
		super("Final Grade Calculator");
		initComponents();
	}

	public FinalGradeCalculator(String title) {
		super(title);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		continueBttn = new javax.swing.JButton();
		questionLabel = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox<>();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		calcBttn = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jLabel11 = new javax.swing.JLabel();
		jLabel22 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel33 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		titleLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		continueBttn.setText("Continue");
		continueBttn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				continueBttnActionPerformed(evt);
			}
		});
		continueBttn.registerKeyboardAction(new java.awt.event.ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				continueBttnActionPerformed(e);
			}

		}, javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0),
				javax.swing.JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);

		questionLabel.setText("Choose Which Action You Would Like to do: ");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "Final Exam Grade Required", "Overall Grade After Exam" }));

		jLabel1.setText("");

		jLabel2.setText("");

		jLabel3.setText("");

		calcBttn.setText("Calculate");
		calcBttn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				calcBttnActionPerformed(evt);
			}
		});
		calcBttn.registerKeyboardAction(new java.awt.event.ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				calcBttnActionPerformed(e);
			}

		}, javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0),
				javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW);

		jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jTextField1FocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				jTextField1FocusLost(evt);
			}
		});

		jLabel11.setText("jLabel1");

		jLabel22.setText("jLabel1");

		jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jTextField2FocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				jTextField2FocusLost(evt);
			}
		});

		jLabel33.setText("jLabel1");

		jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jTextField3FocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				jTextField3FocusLost(evt);
			}
		});

		titleLabel.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 18)); // NOI18N
		titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		titleLabel.setText("FINAL GRADE CALCULATOR");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(calcBttn, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(layout.createSequentialGroup().addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addComponent(questionLabel)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jComboBox1, 0, 186, Short.MAX_VALUE))
										.addComponent(continueBttn, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(
												titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addGroup(layout.createSequentialGroup().addComponent(jLabel3)
														.addGap(18, 18, 18).addComponent(jTextField3))
												.addGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														layout.createSequentialGroup().addComponent(jLabel2)
																.addGap(18, 18, 18).addComponent(jTextField2))
												.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
														.createSequentialGroup().addComponent(jLabel1)
														.addGap(18, 18, 18).addComponent(jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE, 286,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))))))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(questionLabel).addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(18, 18, 18).addComponent(continueBttn).addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
						.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addGap(18, 18, 18).addComponent(calcBttn).addContainerGap()));

		pack();

		javax.swing.JLabel[] labels = new javax.swing.JLabel[] { jLabel1, jLabel11, jLabel2, jLabel22, jLabel3,
				jLabel33 };
		for (javax.swing.JLabel x : labels) {
			x.setVisible(false);
		}
		calcBttn.setVisible(false);
		jTextField1.setVisible(false);
		jTextField2.setVisible(false);
		jTextField3.setVisible(false);

		setSize(getWidth(), 175);
		setLocationRelativeTo(null);
	}// </editor-fold>

	private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {
		// TODO add your handling code here:
		if (jComboBox1.getSelectedItem().equals("Overall Grade After Exam")) {
			if (jTextField1.getText().equals("(e.g. 89.5)")) {
				jTextField1.setText("");
			}
		} else {
			if (jTextField1.getText().equals("(e.g. 92.4)")) {
				jTextField1.setText("");
			}
		}
	}

	private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {
		// TODO add your handling code here:
		if (jComboBox1.getSelectedItem().equals("Overall Grade After Exam")) {
			if (jTextField1.getText().isEmpty()) {
				jTextField1.setText("(e.g. 89.5)");
			}
		} else {
			if (jTextField1.getText().isEmpty()) {
				jTextField1.setText("(e.g. 92.4)");
			}
		}
	}

	private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {
		// TODO add your handling code here:
		if (jComboBox1.getSelectedItem().equals("Overall Grade After Exam")) {
			if (jTextField2.getText().equals("(e.g. 93)")) {
				jTextField2.setText("");
			}
		} else {
			if (jTextField2.getText().equals("(e.g. 90)")) {
				jTextField2.setText("");
			}
		}
	}

	private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {
		// TODO add your handling code here:
		if (jComboBox1.getSelectedItem().equals("Overall Grade After Exam")) {
			if (jTextField2.getText().isEmpty()) {
				jTextField2.setText("(e.g. 93)");
			}
		} else {
			if (jTextField2.getText().isEmpty()) {
				jTextField2.setText("(e.g. 90)");
			}
		}
	}

	private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {
		// TODO add your handling code here
		if (jTextField3.getText().equals("(e.g. 10)")) {
			jTextField3.setText("");
		}
	}

	private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {
		// TODO add your handling code here:
		if (jComboBox1.getSelectedItem().toString().equals("Overall Grade After Exam")) {
			if (jTextField3.getText().isEmpty()) {
				jTextField3.setText("(e.g. 89.5)");
			}
		} else {
			if (jTextField3.getText().isEmpty()) {
				jTextField3.setText("(e.g. 10)");
			}
		}
	}

	private void continueBttnActionPerformed(java.awt.event.ActionEvent evt) {
		String selected = jComboBox1.getSelectedItem().toString();
		continueBttn.setVisible(false);
		javax.swing.JLabel[] labels = new javax.swing.JLabel[] { jLabel1, jLabel11, jLabel2, jLabel22, jLabel3,
				jLabel33 };
		for (javax.swing.JLabel x : labels) {
			x.setVisible(true);
		}
		jComboBox1.setEnabled(false);
		calcBttn.setVisible(true);
		jTextField1.setVisible(true);
		jTextField2.setVisible(true);
		jTextField3.setVisible(true);

		calcBttn.requestFocus();

		if (selected.equals("Final Exam Grade Required")) {
			jTextField1.setText("(e.g. 92.4)");
			jTextField2.setText("(e.g. 90)");
			jTextField3.setText("(e.g. 10)");
			jLabel1.setText("Your current grade is");
			jLabel11.setText("%.");
			jLabel2.setText("You want (at least) a");
			jLabel22.setText("% in the class.");
			jLabel3.setText("Your final is worth");
			jLabel33.setText("% of your grade.");

			// int max = getWidth();
			//
			//
			//
			// if((jLabel1.getWidth() + jLabel11.getWidth() + jTextField1.getWidth()) > max)
			// {
			// max = jLabel1.getWidth() + jLabel11.getWidth() + jTextField1.getWidth();
			// }
			// if((jLabel2.getWidth() + jLabel22.getWidth() + jTextField2.getWidth()) > max)
			// {
			// max = jLabel2.getWidth() + jLabel22.getWidth() + jTextField2.getWidth();
			// }
			// if((jLabel3.getWidth() + jLabel33.getWidth() + jTextField3.getWidth()) > max)
			// {
			// max = jLabel3.getWidth() + jLabel33.getWidth() + jTextField3.getWidth();
			// }
			// max += 75;
			// System.out.println(getWidth());
			// System.out.println(max);

			setSize(538, 325);
		} else {
			jTextField1.setText("(e.g. 89.5)");
			jTextField2.setText("(e.g. 93)");
			jTextField3.setText("(e.g. 10)");
			jLabel1.setText("Your grade was");
			jLabel11.setText("% before.");
			jLabel2.setText("You got a");
			jLabel22.setText("% on the final.");
			jLabel3.setText("Your final is worth");
			jLabel33.setText("% of your grade.");
			setSize(525, 325);
		}
	}

	private void calcBttnActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (jComboBox1.getSelectedItem().equals("Final Exam Grade Required")) {
			double c = Double.parseDouble(jTextField1.getText()) / 100;
			double d = Double.parseDouble(jTextField2.getText()) / 100;
			double w = Double.parseDouble(jTextField3.getText()) / 100;

			double result = d - (1.0 - w) * c;
			result = result / w;
			result *= 100;
			result = (double) Math.round(result * 100) / 100;
			String x = "You will need to score at least " + result + "% on your final to get a " + jTextField2.getText()
					+ "% overall.";
			new ErrorPopup(x).setVisible(true);
		} else {
			Double c = Double.parseDouble(jTextField1.getText()), f = Double.parseDouble(jTextField2.getText()),
					w = Double.parseDouble(jTextField3.getText());

			Double result = (100 - w) * c + (w * f);
			new ErrorPopup("Your overall course grade is " + result / 100 + "%.").setVisible(true);
		}
	}

	private void darkTheme() {

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FinalGradeCalculator.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FinalGradeCalculator.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FinalGradeCalculator.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FinalGradeCalculator.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FinalGradeCalculator().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton calcBttn;
	private javax.swing.JButton continueBttn;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel33;
	private javax.swing.JLabel titleLabel;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JLabel questionLabel;
	// End of variables declaration
}
