package main;

import javax.swing.JLabel;

import algorithm.Algorithms;
import popups.ErrorPopup;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Roshan
 */
@SuppressWarnings("serial")
public class NewSiteWindow extends javax.swing.JFrame {

	/**
	 * Creates new form NewSiteWindow
	 */

	boolean isUpdate;
	String key;
	int row;

	public NewSiteWindow(boolean isUpdate) {
		super("Project Portal");
		this.isUpdate = isUpdate;
		initComponents();
	}

	public NewSiteWindow(String key, boolean isUpdate) {
		super("Project Portal");
		this.isUpdate = isUpdate;
		this.key = key;
		this.row = Algorithms.getInstance().findRow(Algorithms.getInstance().allData, 0, this.key);
		// System.out.println(Arrays.toString(Algorithms.getInstance().allData[row]));
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		urlLabel = new javax.swing.JLabel();
		urlField = new javax.swing.JTextField();
		nameLabel = new javax.swing.JLabel();
		siteNameField = new javax.swing.JTextField();
		categoryLabel = new javax.swing.JLabel();
		categoryComboBox = new javax.swing.JComboBox<>();
		add_updateBttn = new javax.swing.JButton();
		exitBttn = new javax.swing.JButton();
		usernameLabel = new javax.swing.JLabel();
		userNameField = new javax.swing.JTextField();
		passwordLabel = new javax.swing.JLabel();
		passwordField = new javax.swing.JPasswordField();
		showBttn = new javax.swing.JButton();
		userNameIdComboBox = new javax.swing.JComboBox<>();
		passwordIDComboBox = new javax.swing.JComboBox<>();
		htmlIdLabel = new javax.swing.JLabel();
		loginIdComboBox = new javax.swing.JComboBox<>();
		loginBttnLabel = new javax.swing.JLabel();
		userNameIDLabel = new javax.swing.JLabel();
		passwordIDLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		darkTheme();

		urlLabel.setText("URL:");

		urlField.setText("https://");

		nameLabel.setText("Name: ");

		categoryLabel.setText("Category: ");

		categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "GOOGLE", "CUSTOM WITH GOOGLE USER AND PASS", "DESKTOP APPLICATON", "CUSTOM" }));
		categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				categoryComboBoxActionPerformed();
			}
		});

		if (isUpdate) {
			add_updateBttn.setText("UPDATE");
			categoryComboBox.setSelectedItem(Algorithms.getInstance().allData[this.row][2]);
		} else {
			add_updateBttn.setText("ADD");
		}

		add_updateBttn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				add_updateBttnActionPerformed(evt);
			}
		});

		exitBttn.setText("EXIT");
		exitBttn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitBttnActionPerformed(evt);
			}
		});

		usernameLabel.setText("Username Field:");

		passwordLabel.setText("Password Field:");

		showBttn.setText("SHOW");
		showBttn.addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mousePressed(java.awt.event.MouseEvent evt) {
				showBttnMousePressed(evt);
			}

			@Override
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				showBttnMouseReleased(evt);
			}
		});

		userNameIdComboBox.setEditable(true);
		userNameIdComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEFAULT/NONE" }));

		passwordIDComboBox.setEditable(true);
		passwordIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEFAULT/NONE" }));

		htmlIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		htmlIdLabel.setText("HTML ID:");

		loginIdComboBox.setEditable(true);
		loginIdComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DEFAULT/NONE" }));

		loginBttnLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		loginBttnLabel.setText("Login Button ID");

		userNameIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		userNameIDLabel.setText("Username ID");

		passwordIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		passwordIDLabel.setText("Password ID");

		if (categoryComboBox.getSelectedItem().equals("CUSTOM WITH GOOGLE USER AND PASS")) {
			userNameIdComboBox.setSelectedItem(Algorithms.getInstance().allData[this.row][3]);
			passwordIDComboBox.setSelectedItem(Algorithms.getInstance().allData[this.row][4]);
			loginIdComboBox.setSelectedItem(Algorithms.getInstance().allData[this.row][5]);
		} else if (categoryComboBox.getSelectedItem().equals("CUSTOM")) {
			userNameIdComboBox.setSelectedItem(Algorithms.getInstance().allData[this.row][3]);
			passwordIDComboBox.setSelectedItem(Algorithms.getInstance().allData[this.row][4]);
			userNameField.setText(Algorithms.getInstance().allData[this.row][5]);
			passwordField.setText(Algorithms.getInstance().allData[this.row][6]);
			loginIdComboBox.setSelectedItem(Algorithms.getInstance().allData[this.row][7]);
		}

		categoryComboBoxActionPerformed();

		if (isUpdate) {
			urlField.setText(algorithm.Algorithms.getInstance().nameToURL.get(this.key).toString());
			siteNameField.setText(this.key);
			siteNameField.setEditable(false);
		}

		if (!new String(passwordField.getPassword()).isEmpty()) {
			showBttn.setVisible(false);
		}
	}// </editor-fold>

	private void add_updateBttnActionPerformed(java.awt.event.ActionEvent evt) {
		String key = siteNameField.getText();
		String value = urlField.getText();
		boolean err = false;
		if (key.isEmpty()) {
			err = true;
			new ErrorPopup("Please fill in all fields.").setVisible(true);
		}
		if (!categoryComboBox.getSelectedItem().equals("DESKTOP APPLICATON")) {
			if (!value.startsWith("https://")) {
				value = "https://" + value;
			}
		}
		if (!err) {
			if (add_updateBttn.getText().equals("ADD")) {
				int length = Algorithms.getInstance().allData.length + 1;
				String[][] array = new String[length][];
				for (int i = 0; i < Algorithms.getInstance().allData.length; i++) {
					array[i] = Algorithms.getInstance().allData[i];
				}
				java.util.ArrayList<String> newElement = new java.util.ArrayList<String>();
				newElement.add(siteNameField.getText());
				newElement.add(value);
				newElement.add(categoryComboBox.getSelectedItem().toString());
				System.out.println(newElement);
				if (categoryComboBox.getSelectedItem().equals("CUSTOM WITH GOOGLE USER AND PASS")) {
					newElement.add(userNameIdComboBox.getSelectedItem().toString());
					newElement.add(passwordIDComboBox.getSelectedItem().toString());
					newElement.add(loginIdComboBox.getSelectedItem().toString());
				} else if (categoryComboBox.getSelectedItem().equals("CUSTOM")) {
					newElement.add(userNameIdComboBox.getSelectedItem().toString());
					newElement.add(passwordIDComboBox.getSelectedItem().toString());
					newElement.add(userNameField.getText());
					newElement.add(new String(passwordField.getPassword()));
					newElement.add(loginIdComboBox.getSelectedItem().toString());
				}
				array[length - 1] = newElement.toArray(new String[newElement.size()]);
				Algorithms.getInstance().allData = array;

			} else {
				// algorithm.Algorithms.getInstance().nameToURL.replace(key, value);
				int x = row;
				Algorithms.getInstance().allData[x][0] = key;
				Algorithms.getInstance().allData[x][1] = value;
				Algorithms.getInstance().allData[x][2] = categoryComboBox.getSelectedItem().toString();
				if (categoryComboBox.getSelectedItem().equals("CUSTOM WITH GOOGLE USER AND PASS")) {
					Algorithms.getInstance().allData[x][3] = userNameIdComboBox.getSelectedItem().toString();
					Algorithms.getInstance().allData[x][4] = passwordIDComboBox.getSelectedItem().toString();
					Algorithms.getInstance().allData[x][5] = loginIdComboBox.getSelectedItem().toString();
				}
				if (categoryComboBox.getSelectedItem().equals("CUSTOM")) {
					Algorithms.getInstance().allData[x][3] = userNameIdComboBox.getSelectedItem().toString();
					Algorithms.getInstance().allData[x][4] = passwordIDComboBox.getSelectedItem().toString();
					Algorithms.getInstance().allData[x][5] = userNameField.getText();
					Algorithms.getInstance().allData[x][6] = new String(passwordField.getPassword());
					Algorithms.getInstance().allData[x][7] = loginIdComboBox.getSelectedItem().toString();
				}
			}
			Algorithms.getInstance().updateDictionaryFromArray();
			Algorithms.getInstance().updateTextFile();
			StartupWindow.linkChooser.updateModel();
			exitBttn.doClick();
		}
	}

	private void categoryComboBoxActionPerformed() {
		urlLabel.setText("URL:");
		urlField.setText("https://");
		if (categoryComboBox.getSelectedItem().equals("DESKTOP APPLICATON")) {
			urlLabel.setText("Path:");
			urlField.setText("");
		}

		if (categoryComboBox.getSelectedItem().equals("GOOGLE")
				|| categoryComboBox.getSelectedItem().equals("DESKTOP APPLICATON")) {
			userNameField.setVisible(false);
			usernameLabel.setVisible(false);
			htmlIdLabel.setVisible(false);
			userNameIdComboBox.setVisible(false);
			passwordIDComboBox.setVisible(false);
			passwordLabel.setVisible(false);
			passwordField.setVisible(false);
			showBttn.setVisible(false);
			userNameField.setVisible(false);
			userNameIDLabel.setVisible(false);
			userNameIdComboBox.setVisible(false);
			usernameLabel.setVisible(false);
			javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
			getContentPane().setLayout(layout);
			layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
							.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addComponent(add_updateBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 130,
											javax.swing.GroupLayout.PREFERRED_SIZE)
									.addGroup(layout.createSequentialGroup().addGroup(
											layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
													.addComponent(urlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
															javax.swing.GroupLayout.PREFERRED_SIZE)
													.addComponent(nameLabel).addComponent(categoryLabel))
											.addGap(34, 34, 34)
											.addGroup(layout
													.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
													.addComponent(exitBttn, javax.swing.GroupLayout.Alignment.TRAILING,
															javax.swing.GroupLayout.PREFERRED_SIZE, 130,
															javax.swing.GroupLayout.PREFERRED_SIZE)
													.addGroup(layout.createSequentialGroup().addGap(30, 30, 30)
															.addGroup(layout
																	.createParallelGroup(
																			javax.swing.GroupLayout.Alignment.LEADING,
																			false)
																	.addComponent(urlField)
																	.addComponent(categoryComboBox, 0,
																			javax.swing.GroupLayout.DEFAULT_SIZE,
																			Short.MAX_VALUE)
																	.addComponent(siteNameField,
																			javax.swing.GroupLayout.Alignment.TRAILING,
																			javax.swing.GroupLayout.PREFERRED_SIZE, 299,
																			javax.swing.GroupLayout.PREFERRED_SIZE))))))));
			layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(layout.createSequentialGroup().addGap(30, 30, 30)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
									.addComponent(siteNameField).addComponent(
											nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
											javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
							.addGap(10, 10, 10)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(layout.createSequentialGroup()
											.addComponent(urlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
													javax.swing.GroupLayout.PREFERRED_SIZE)
											.addGap(10, 10, 10).addComponent(categoryLabel,
													javax.swing.GroupLayout.PREFERRED_SIZE, 27,
													javax.swing.GroupLayout.PREFERRED_SIZE))
									.addGroup(layout.createSequentialGroup()
											.addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE,
													javax.swing.GroupLayout.DEFAULT_SIZE,
													javax.swing.GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
											.addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
													javax.swing.GroupLayout.DEFAULT_SIZE,
													javax.swing.GroupLayout.PREFERRED_SIZE)))
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
									.addComponent(add_updateBttn).addComponent(exitBttn))
							.addContainerGap()));

			pack();
		} else {
			userNameField.setVisible(true);
			usernameLabel.setVisible(true);
			htmlIdLabel.setVisible(true);
			userNameIdComboBox.setVisible(true);
			passwordIDComboBox.setVisible(true);
			passwordLabel.setVisible(true);
			passwordField.setVisible(true);
			showBttn.setVisible(true);
			userNameField.setVisible(true);
			userNameIDLabel.setVisible(true);
			userNameIdComboBox.setVisible(true);
			usernameLabel.setVisible(true);
			javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
			getContentPane().setLayout(layout);
			layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
							.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
							.addGroup(layout.createSequentialGroup()
									.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
											.addComponent(urlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58,
													javax.swing.GroupLayout.PREFERRED_SIZE)
											.addComponent(nameLabel).addComponent(categoryLabel)
											.addComponent(usernameLabel).addComponent(passwordLabel))
									.addGap(30, 30, 30)
									.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
											.addGroup(layout
													.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
															false)
													.addComponent(urlField)
													.addComponent(categoryComboBox, 0,
															javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
													.addComponent(siteNameField,
															javax.swing.GroupLayout.Alignment.TRAILING,
															javax.swing.GroupLayout.PREFERRED_SIZE, 299,
															javax.swing.GroupLayout.PREFERRED_SIZE))
											.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
													.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
													.addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE,
															299, javax.swing.GroupLayout.PREFERRED_SIZE)
													.addGroup(layout.createSequentialGroup()
															.addComponent(passwordField,
																	javax.swing.GroupLayout.PREFERRED_SIZE, 211,
																	javax.swing.GroupLayout.PREFERRED_SIZE)
															.addPreferredGap(
																	javax.swing.LayoutStyle.ComponentPlacement.RELATED)
															.addComponent(showBttn,
																	javax.swing.GroupLayout.PREFERRED_SIZE, 79,
																	javax.swing.GroupLayout.PREFERRED_SIZE)))))
							.addComponent(add_updateBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 128,
									javax.swing.GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addComponent(exitBttn, javax.swing.GroupLayout.DEFAULT_SIZE,
											javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(passwordIDComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0,
											149, Short.MAX_VALUE)
									.addComponent(htmlIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
											javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(userNameIdComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
											Short.MAX_VALUE)
									.addComponent(loginIdComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
											Short.MAX_VALUE)
									.addComponent(userNameIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
											javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(loginBttnLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
											javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
									.addComponent(passwordIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
											javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
							.addContainerGap()));
			layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(htmlIdLabel)
							.addGap(14, 14, 14)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
									.addGroup(
											layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
													.addComponent(siteNameField).addComponent(nameLabel,
															javax.swing.GroupLayout.DEFAULT_SIZE,
															javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
									.addComponent(loginBttnLabel))
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
									.addGroup(layout.createSequentialGroup()
											.addComponent(urlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29,
													javax.swing.GroupLayout.PREFERRED_SIZE)
											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
											.addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
													javax.swing.GroupLayout.PREFERRED_SIZE)
											.addGap(12, 12, 12)
											.addGroup(layout
													.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
													.addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE,
															javax.swing.GroupLayout.DEFAULT_SIZE,
															javax.swing.GroupLayout.PREFERRED_SIZE)
													.addComponent(usernameLabel)))
									.addGroup(layout.createSequentialGroup().addGroup(layout
											.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
											.addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE,
													javax.swing.GroupLayout.DEFAULT_SIZE,
													javax.swing.GroupLayout.PREFERRED_SIZE)
											.addComponent(loginIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
													javax.swing.GroupLayout.DEFAULT_SIZE,
													javax.swing.GroupLayout.PREFERRED_SIZE))
											.addGroup(layout
													.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
													.addGroup(layout.createSequentialGroup()
															.addPreferredGap(
																	javax.swing.LayoutStyle.ComponentPlacement.RELATED)
															.addGroup(layout
																	.createParallelGroup(
																			javax.swing.GroupLayout.Alignment.BASELINE)
																	.addComponent(categoryComboBox,
																			javax.swing.GroupLayout.PREFERRED_SIZE,
																			javax.swing.GroupLayout.DEFAULT_SIZE,
																			javax.swing.GroupLayout.PREFERRED_SIZE)
																	.addComponent(userNameIDLabel)))
													.addGroup(layout.createSequentialGroup().addGap(30, 30, 30)
															.addComponent(userNameIdComboBox,
																	javax.swing.GroupLayout.PREFERRED_SIZE,
																	javax.swing.GroupLayout.DEFAULT_SIZE,
																	javax.swing.GroupLayout.PREFERRED_SIZE)))
											.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
											.addComponent(passwordIDLabel)))
							.addGap(2, 2, 2)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
									.addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE,
											javax.swing.GroupLayout.DEFAULT_SIZE,
											javax.swing.GroupLayout.PREFERRED_SIZE)
									.addComponent(showBttn)
									.addComponent(passwordIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
											javax.swing.GroupLayout.DEFAULT_SIZE,
											javax.swing.GroupLayout.PREFERRED_SIZE)
									.addComponent(passwordLabel))
							.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
							.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
									.addComponent(add_updateBttn).addComponent(exitBttn))
							.addContainerGap()));

			pack();
		}
	}

	private void showBttnMousePressed(java.awt.event.MouseEvent evt) {
		passwordField.setEchoChar((char) 0);
	}

	private void showBttnMouseReleased(java.awt.event.MouseEvent evt) {
		passwordField.setEchoChar('*');
	}

	private void exitBttnActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	private void darkTheme() {
		JLabel[] labels = new JLabel[] {};

	}

	// Variables declaration - do not modify
	private javax.swing.JButton add_updateBttn;
	private javax.swing.JComboBox<String> categoryComboBox;
	private javax.swing.JLabel categoryLabel;
	private javax.swing.JButton exitBttn;
	private javax.swing.JLabel htmlIdLabel;
	private javax.swing.JLabel loginBttnLabel;
	private javax.swing.JComboBox<String> loginIdComboBox;
	private javax.swing.JLabel nameLabel;
	private javax.swing.JPasswordField passwordField;
	private javax.swing.JComboBox<String> passwordIDComboBox;
	private javax.swing.JLabel passwordIDLabel;
	private javax.swing.JLabel passwordLabel;
	private javax.swing.JButton showBttn;
	private javax.swing.JTextField siteNameField;
	private javax.swing.JTextField urlField;
	private javax.swing.JLabel urlLabel;
	private javax.swing.JTextField userNameField;
	private javax.swing.JLabel userNameIDLabel;
	private javax.swing.JComboBox<String> userNameIdComboBox;
	private javax.swing.JLabel usernameLabel;
	// End of variables declaration
}
